apiVersion: v1
entries:
  brc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-18T11:57:13.443019607Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 03cb3fa1fbb6946308c927312bd82d79a8c64388fdfdddf44e0b12ec20692b6b
    home: brc.zaakonline.nl
    icon: brc.zaakonline.nl
    name: brc
    urls:
    - brc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-18T11:57:13.440387707Z"
